### ISSUE TITLE
implement SpecLibFlat.remove_unused_fragments()

### ISSUE THREAD

**Issue by GeorgWa** [MannLabs/alphabase#146]
Currently, `remove_unused_fragments` is only implemented for dense libraries.
An implementation for flat libraries would be very usefull and should be easy to implement.

**Comment by jalew188** [comment]
I think we already have args `frag_start_col` and `frag_start_col` for different cases, see
https://github.com/MannLabs/alphabase/blob/main/alphabase/peptide/fragment.py#L867

**Comment by jalew188** [comment]
I designed this for spectrum_df's `peak_start_idx` and `peak_stop_idx`, flat_lib case should be similar

**Comment by GeorgWa** [comment]
I agree, it's most likely a very simple function and we can use https://github.com/MannLabs/alphabase/blob/main/alphabase/peptide/fragment.py#L867

**Comment by jalew188** [comment]
Is this issue still required? @GeorgWa

**Comment by GeorgWa** [comment]
It was implemented in #149 👍
