### ISSUE TITLE
Loading library from hdf to translate to tsv fails with KeyError

### ISSUE THREAD

**Issue by JuliaS92** [MannLabs/alphabase#211]
**Describe the bug**
I am trying to read a spectral library saved to .hdf to translate it to a .tsv for use with DIA-NN. When running translate_to_tsv I get a key error instead:
```
--> [277]df["ModifiedPeptide"] = speclib._precursor_df[
    [278]     ["sequence", "mods", "mod_sites"]
    [279] ].apply(
    [280]    create_modified_sequence,
    [281]     axis=1,
    [282]     translate_mod_dict=translate_mod_dict,
    [283]     mod_sep="[]",
    [284] )

KeyError: "None of [Index(['sequence', 'mods', 'mod_sites'], dtype='object')] are in the [columns]"
```

**To Reproduce**
1. I ran this previously to predict and save the library:
```
from peptdeep.protein.fasta import PredictSpecLibFasta
fasta_lib = PredictSpecLibFasta(...)
fasta_lib.predict_all()
fasta_lib.save_hdf("filename.hdf")
```
2. Now I am trying to read and save using alphabase:
```
from alphabase.spectral_library.base import SpecLibBase
speclib = SpecLibBase()
speclib.load_hdf("filename")
from peptdeep.spec_lib.translate import translate_to_tsv #pointing to alphabase
translate_to_tsv(speclib, "filename.tsv", keep_k_highest_fragments=12, min_frag_intensity=0.001,
)
```

**Expected behavior**
This should behave exaclty the same as if I had the original PredictSpecLibFasta object as input to translate_to_tsv.

**Logs**
See above.

**Version (please complete the following information):**
 - PIP installed
 - If no log is available, provide the following:
   - Platform information
     - system    Sonoma
     - release   14.5
   - Python information:
     - alphabase                 1.2.5
     - alpharaw                  0.4.5
     - numpy                     2.0.1
     - pandas                    2.2.2
     - peptdeep                  1.2.1
     - torch                     2.4.0

**Additional context**
I used mods not in the original constants table, but had updated the table on disc to make prediction work.

**Comment by GeorgWa** [comment]
Originally to maximize performance only the most important columns were read from an `hdf`. 

This has been adressed by https://github.com/MannLabs/alphabase/pull/196 and you can switch to the most recent dev version.
Otherwise set `load_mod_seq=True`

**Comment by JuliaS92** [comment]
Thank you for the quick reply :)

**Comment by GeorgWa** [comment]
Thank you for the detailed bug report! This is realy helpful for us and future users who will find it by google etc.
