### ISSUE TITLE
msgfplus rescoring support or AlphaPeptDeep format example

### ISSUE THREAD

**Issue by gsaxena888** [MannLabs/alphabase#62]
I'd like to use the output of the msgfplus search engine (which I can convert to percolator format) as an input toAlphaPeptDeep's **rescoring** module. However, I don't think that either msgfplus output or percolator output is supported? Thoughts?

(One idea I had was to write a converter from msgfplus (or percolator) to the "AlphaPeptDeep" format, but I couldn't find an example file for AlphaPeptDeep and documentation for what fields are required so that I could create such a converter. Thoughts?)

**Comment by jalew188** [comment]
Is this mzid supported by pyteomics?

**Comment by jalew188** [comment]
Close this issue as there are no activities for a long time
