### ISSUE TITLE
modloss_importance in modification.tsv

### ISSUE THREAD

**Issue by yangkl96** [MannLabs/alphabase#83]
Were the modloss_importance values derived from somewhere or just arbitrary? I noticed they were only set to non-zero values for phospho and glygly. Does this mean that unless manually changed in modification.tsv to be 1, b/y ions with modlosses will be ignored?

Thanks,
Kevin

**Comment by jalew188** [comment]
1. In AlphaPeptDeep, modloss_importance is controled by `modloss_importance_level` in the settings: https://github.com/MannLabs/alphapeptdeep/blob/main/peptdeep/constants/default_settings.yaml#L41
2. The fragment masses and predicted intensities will be zero for all PTMs with `modloss_importance < modloss_importance_level`
3. To change the `modloss_importance` values, you can either modify the tsv or do it programmly:
```
from alphabase.constants.modification import MOD_DF, update_all_by_MOD_DF, MOD_LOSS_IMPORTANCE

MOD_DF.loc['Oxidation@M','modloss_importance'] = 1000
update_all_by_MOD_DF()
print(MOD_LOSS_IMPORTANCE['Oxidation@M'])
```

**Comment by yangkl96** [comment]
Thanks for explaining!
